// FFX Forensic Report - Generated by FFX Forensic File Xplorer
// Classification: LAW ENFORCEMENT SENSITIVE
// 
// To compile this file to PDF:
//   typst compile report.typ report.pdf
//
// Or use Typst's watch mode for live preview:
//   typst watch report.typ

#set document(
  title: "Digital Forensic Examination Report",
  author: "Alex Johnson",
)

#set page(
  paper: "us-letter",
  margin: (x: 1in, y: 1in),
  header: align(center)[
    #set text(size: 9pt, weight: "bold", fill: purple)
    LAW ENFORCEMENT SENSITIVE
  ],
  footer: context [
    #set text(size: 9pt)
    #align(center)[
      #counter(page).display("1 of 1", both: true)
    ]
  ],
)

#set text(
  font: "New Computer Modern",
  size: 11pt,
)

#set heading(numbering: "1.1")

#set par(
  justify: true,
  leading: 0.65em,
)

// Custom styling functions
#let info-box(title, content) = {
  block(
    fill: luma(245),
    inset: 10pt,
    radius: 4pt,
    width: 100%,
  )[
    *#title*
    #v(0.5em)
    #content
  ]
}

#let severity-badge(level) = {
  let (color, label) = if level == "Critical" {
    (rgb("#dc2626"), "CRITICAL")
  } else if level == "High" {
    (rgb("#ea580c"), "HIGH")  
  } else if level == "Medium" {
    (rgb("#ca8a04"), "MEDIUM")
  } else if level == "Low" {
    (rgb("#16a34a"), "LOW")
  } else {
    (rgb("#6b7280"), "INFO")
  }
  box(
    fill: color,
    inset: (x: 6pt, y: 3pt),
    radius: 3pt,
  )[#text(fill: white, weight: "bold", size: 8pt)[#label]]
}


// Title Page
#align(center)[
  #v(2in)
  
  #text(size: 24pt, weight: "bold")[
    Digital Forensic Examination Report
  ]
  
  #v(0.5em)
  
  #text(size: 14pt)[
    Report \#FR-2026-0001 | Version 1.0
  ]
  
  #v(2em)
  
  #text(size: 12pt)[
    Case Number: *2026-CF-00123*
  ]
  
  #v(0.5em)
  
  #text(size: 12pt)[
    State v. John Doe
  ]
  
  #v(3em)
  
  #text(size: 11pt)[
    Prepared by: \
    *Alex Johnson* \
    Senior Digital Forensic Examiner \
    Metro Police Forensic Lab
  ]
  
  #v(2em)
  
  #text(size: 10pt)[
    Generated: 2026-01-04
  ]
  
  #v(fill)
  
  #text(size: 12pt, weight: "bold")[
    LAW ENFORCEMENT SENSITIVE
  ]
]

#pagebreak()


#outline(title: "Table of Contents", depth: 2)
#pagebreak()

= Case Information

#table(
  columns: (auto, 1fr),
  stroke: none,
  row-gutter: 0.5em,
  [*Case Number*], [2026-CF-00123],
  [*Case Name*], [State v. John Doe],
  [*Agency*], [Metro Police Department],
  [*Requestor*], [Det. Jane Smith],
  [*Investigation Type*], [Fraud Investigation],
)

== Examiner

#table(
  columns: (auto, 1fr),
  stroke: none,
  row-gutter: 0.5em,
  [*Name*], [Alex Johnson],
  [*Title*], [Senior Digital Forensic Examiner],
  [*Organization*], [Metro Police Forensic Lab],
  [*Email*], [ajohnson\@metro.gov],
  [*Phone*], [(555) 123-4567],
)

*Certifications:* EnCE (EnCase Certified Examiner), GCFE (GIAC Certified Forensic Examiner), ACE (AccessData Certified Examiner)

#pagebreak()

= Executive Summary

This report documents the forensic examination of digital evidence seized pursuant to Search Warrant \#2026-SW-456. The examination revealed several artifacts of evidentiary value including documents, communications, and internet history relevant to the investigation. Key findings include evidence of document manipulation and communication records between subjects of interest.

#pagebreak()

= Scope of Examination

The scope of this examination was limited to the recovery and analysis of digital artifacts from the submitted evidence items. This examination focused on document recovery, communication analysis, and timeline reconstruction.

#pagebreak()

= Methodology

Standard forensic methodology was employed throughout this examination:
1. Evidence intake and chain of custody documentation
2. Forensic imaging using write-blocking hardware
3. Hash verification of forensic images
4. Systematic artifact extraction and analysis
5. Documentation and report generation

#pagebreak()

= Evidence Examined

#table(
  columns: (auto, 2fr, auto, auto, auto),
  align: (left, left, left, left, left),
  fill: (x, y) => if y == 0 { luma(230) } else { none },
  [*ID*], [*Description*], [*Type*], [*Serial*], [*Capacity*],
  [E001], [Dell Latitude laptop computer], [Laptop], [SN-DELL-2024-001], [512 GB SSD],
  [E002], [Samsung Galaxy S23 smartphone], [Mobile Phone], [IMEI-123456789012345], [256 GB],
)

== Evidence E001 Details

*Hash Values:*

#table(
  columns: (auto, 1fr),
  [*Algorithm*], [*Value*],
  [MD5], [```d41d8cd98f00b204e9800998ecf8427e```],
  [SHA-256], [```e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855```],
)

*Notes:* Laptop was powered off when received. Battery at 45%.

== Evidence E002 Details

*Notes:* Device was in airplane mode. PIN lock enabled.

#pagebreak()

= Findings

== F001 - Deleted Financial Documents Recovered

#severity-badge("High") #h(1em) *Category:* Deleted Data

Analysis of unallocated space revealed 47 deleted Microsoft Excel spreadsheets containing financial records. These documents appear to have been deleted on 2025-12-15, approximately one week before the search warrant was executed. Document metadata indicates they were created by user 'JDoe'.

*Related Files:*
- `/Users/JDoe/Documents/Financials/Q4\_2025\_Report.xlsx`
- `/Users/JDoe/Documents/Financials/Transactions\_Dec.xlsx`

*Supporting Evidence:* E001

== F002 - Encrypted Communication Application

#severity-badge("Medium") #h(1em) *Category:* Communication

Signal messaging application was installed on both the laptop and mobile device. Message database was recovered from the mobile device backup. Analysis revealed communications with 3 contacts during the relevant time period.

*Supporting Evidence:* E001, E002

== F003 - Browser History Analysis

#severity-badge("Low") #h(1em) *Category:* Internet History

Chrome browser history shows searches related to 'how to permanently delete files' and 'forensic file recovery' on 2025-12-14, the day before the deleted documents were removed.

*Related Files:*
- `/Users/JDoe/AppData/Local/Google/Chrome/User Data/Default/History`

*Supporting Evidence:* E001

#pagebreak()

= Timeline of Events

#table(
  columns: (auto, auto, 2fr, auto),
  fill: (x, y) => if y == 0 { luma(230) } else { none },
  [*Timestamp*], [*Type*], [*Description*], [*Source*],
  [2026-01-04 04:19:50], [File Creation], [Q4 Financial Report created], [NTFS \$MFT],
  [2026-01-04 04:19:50], [Web Search], [Search: 'how to permanently delete files'], [Chrome History],
  [2026-01-04 04:19:50], [File Deletion], [47 Excel files deleted from Documents folder], [NTFS \$MFT / \$UsnJrnl],
)

#pagebreak()

= Tools Used

#table(
  columns: (1fr, auto, 1fr, 2fr),
  fill: (x, y) => if y == 0 { luma(230) } else { none },
  [*Tool*], [*Version*], [*Vendor*], [*Purpose*],
  [FTK Imager], [4.7.1.2], [Exterro], [Forensic imaging and hash verification],
  [EnCase Forensic], [23.4], [OpenText], [Evidence analysis and artifact extraction],
  [FFX Forensic Toolkit], [0.1.0], [CORE Project], [Report generation and timeline analysis],
)

#pagebreak()

= Conclusions

Based on the forensic examination of the submitted evidence, the following conclusions are supported:

1. Financial documents were systematically deleted from the laptop computer approximately one week before the search warrant was executed.

2. Internet search history indicates the user researched file deletion methods the day before the documents were removed.

3. Encrypted communication applications were in use on both devices during the relevant time period.

These findings are presented for investigative purposes and are subject to further analysis as needed.

#pagebreak()


// End of Report
#v(2em)
#align(center)[
  #line(length: 50%)
  #v(1em)
  #text(size: 9pt)[
    This report was generated by *FFX Forensic Toolkit* on 2026-01-04 04:19:50 UTC.
  ]
  #v(0.5em)
  #text(size: 10pt, weight: "bold")[
    LAW ENFORCEMENT SENSITIVE
  ]
]
