// =============================================================================
// CORE-FFX - Forensic File Explorer
// Companion Log Types - Acquisition log file types
// =============================================================================

/**
 * Companion Log Types
 * 
 * Types for parsing and displaying companion log files (.txt files
 * generated by forensic tools alongside evidence containers).
 */

import type { StoredHash, SegmentHash } from "./hash";

// ============================================================================
// Companion Log Info
// ============================================================================

export type CompanionLogInfo = {
  log_path: string;
  created_by?: string;
  case_number?: string;
  evidence_number?: string;
  unique_description?: string;
  examiner?: string;
  notes?: string;
  acquisition_started?: string;
  acquisition_finished?: string;
  verification_started?: string;
  verification_finished?: string;
  stored_hashes: StoredHash[];
  segment_list: string[];
  segment_hashes: SegmentHash[];
};
