/* automatically generated by rust-bindgen 0.72.1 */

pub const ARCHIVE_VERSION_NUMBER: u32 = 3008001;
pub const ARCHIVE_VERSION_ONLY_STRING: &[u8; 6] = b"3.8.1\0";
pub const ARCHIVE_VERSION_STRING: &[u8; 17] = b"libarchive 3.8.1\0";
pub const ARCHIVE_EOF: u32 = 1;
pub const ARCHIVE_OK: u32 = 0;
pub const ARCHIVE_RETRY: i32 = -10;
pub const ARCHIVE_WARN: i32 = -20;
pub const ARCHIVE_FAILED: i32 = -25;
pub const ARCHIVE_FATAL: i32 = -30;
pub const ARCHIVE_FILTER_NONE: u32 = 0;
pub const ARCHIVE_FILTER_GZIP: u32 = 1;
pub const ARCHIVE_FILTER_BZIP2: u32 = 2;
pub const ARCHIVE_FILTER_COMPRESS: u32 = 3;
pub const ARCHIVE_FILTER_PROGRAM: u32 = 4;
pub const ARCHIVE_FILTER_LZMA: u32 = 5;
pub const ARCHIVE_FILTER_XZ: u32 = 6;
pub const ARCHIVE_FILTER_UU: u32 = 7;
pub const ARCHIVE_FILTER_RPM: u32 = 8;
pub const ARCHIVE_FILTER_LZIP: u32 = 9;
pub const ARCHIVE_FILTER_LRZIP: u32 = 10;
pub const ARCHIVE_FILTER_LZOP: u32 = 11;
pub const ARCHIVE_FILTER_GRZIP: u32 = 12;
pub const ARCHIVE_FILTER_LZ4: u32 = 13;
pub const ARCHIVE_FILTER_ZSTD: u32 = 14;
pub const ARCHIVE_COMPRESSION_NONE: u32 = 0;
pub const ARCHIVE_COMPRESSION_GZIP: u32 = 1;
pub const ARCHIVE_COMPRESSION_BZIP2: u32 = 2;
pub const ARCHIVE_COMPRESSION_COMPRESS: u32 = 3;
pub const ARCHIVE_COMPRESSION_PROGRAM: u32 = 4;
pub const ARCHIVE_COMPRESSION_LZMA: u32 = 5;
pub const ARCHIVE_COMPRESSION_XZ: u32 = 6;
pub const ARCHIVE_COMPRESSION_UU: u32 = 7;
pub const ARCHIVE_COMPRESSION_RPM: u32 = 8;
pub const ARCHIVE_COMPRESSION_LZIP: u32 = 9;
pub const ARCHIVE_COMPRESSION_LRZIP: u32 = 10;
pub const ARCHIVE_FORMAT_BASE_MASK: u32 = 16711680;
pub const ARCHIVE_FORMAT_CPIO: u32 = 65536;
pub const ARCHIVE_FORMAT_CPIO_POSIX: u32 = 65537;
pub const ARCHIVE_FORMAT_CPIO_BIN_LE: u32 = 65538;
pub const ARCHIVE_FORMAT_CPIO_BIN_BE: u32 = 65539;
pub const ARCHIVE_FORMAT_CPIO_SVR4_NOCRC: u32 = 65540;
pub const ARCHIVE_FORMAT_CPIO_SVR4_CRC: u32 = 65541;
pub const ARCHIVE_FORMAT_CPIO_AFIO_LARGE: u32 = 65542;
pub const ARCHIVE_FORMAT_CPIO_PWB: u32 = 65543;
pub const ARCHIVE_FORMAT_SHAR: u32 = 131072;
pub const ARCHIVE_FORMAT_SHAR_BASE: u32 = 131073;
pub const ARCHIVE_FORMAT_SHAR_DUMP: u32 = 131074;
pub const ARCHIVE_FORMAT_TAR: u32 = 196608;
pub const ARCHIVE_FORMAT_TAR_USTAR: u32 = 196609;
pub const ARCHIVE_FORMAT_TAR_PAX_INTERCHANGE: u32 = 196610;
pub const ARCHIVE_FORMAT_TAR_PAX_RESTRICTED: u32 = 196611;
pub const ARCHIVE_FORMAT_TAR_GNUTAR: u32 = 196612;
pub const ARCHIVE_FORMAT_ISO9660: u32 = 262144;
pub const ARCHIVE_FORMAT_ISO9660_ROCKRIDGE: u32 = 262145;
pub const ARCHIVE_FORMAT_ZIP: u32 = 327680;
pub const ARCHIVE_FORMAT_EMPTY: u32 = 393216;
pub const ARCHIVE_FORMAT_AR: u32 = 458752;
pub const ARCHIVE_FORMAT_AR_GNU: u32 = 458753;
pub const ARCHIVE_FORMAT_AR_BSD: u32 = 458754;
pub const ARCHIVE_FORMAT_MTREE: u32 = 524288;
pub const ARCHIVE_FORMAT_RAW: u32 = 589824;
pub const ARCHIVE_FORMAT_XAR: u32 = 655360;
pub const ARCHIVE_FORMAT_LHA: u32 = 720896;
pub const ARCHIVE_FORMAT_CAB: u32 = 786432;
pub const ARCHIVE_FORMAT_RAR: u32 = 851968;
pub const ARCHIVE_FORMAT_7ZIP: u32 = 917504;
pub const ARCHIVE_FORMAT_WARC: u32 = 983040;
pub const ARCHIVE_FORMAT_RAR_V5: u32 = 1048576;
pub const ARCHIVE_READ_FORMAT_CAPS_NONE: u32 = 0;
pub const ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_DATA: u32 = 1;
pub const ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_METADATA: u32 = 2;
pub const ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED: i32 = -2;
pub const ARCHIVE_READ_FORMAT_ENCRYPTION_DONT_KNOW: i32 = -1;
pub const ARCHIVE_EXTRACT_OWNER: u32 = 1;
pub const ARCHIVE_EXTRACT_PERM: u32 = 2;
pub const ARCHIVE_EXTRACT_TIME: u32 = 4;
pub const ARCHIVE_EXTRACT_NO_OVERWRITE: u32 = 8;
pub const ARCHIVE_EXTRACT_UNLINK: u32 = 16;
pub const ARCHIVE_EXTRACT_ACL: u32 = 32;
pub const ARCHIVE_EXTRACT_FFLAGS: u32 = 64;
pub const ARCHIVE_EXTRACT_XATTR: u32 = 128;
pub const ARCHIVE_EXTRACT_SECURE_SYMLINKS: u32 = 256;
pub const ARCHIVE_EXTRACT_SECURE_NODOTDOT: u32 = 512;
pub const ARCHIVE_EXTRACT_NO_AUTODIR: u32 = 1024;
pub const ARCHIVE_EXTRACT_NO_OVERWRITE_NEWER: u32 = 2048;
pub const ARCHIVE_EXTRACT_SPARSE: u32 = 4096;
pub const ARCHIVE_EXTRACT_MAC_METADATA: u32 = 8192;
pub const ARCHIVE_EXTRACT_NO_HFS_COMPRESSION: u32 = 16384;
pub const ARCHIVE_EXTRACT_HFS_COMPRESSION_FORCED: u32 = 32768;
pub const ARCHIVE_EXTRACT_SECURE_NOABSOLUTEPATHS: u32 = 65536;
pub const ARCHIVE_EXTRACT_CLEAR_NOCHANGE_FFLAGS: u32 = 131072;
pub const ARCHIVE_EXTRACT_SAFE_WRITES: u32 = 262144;
pub const ARCHIVE_READDISK_RESTORE_ATIME: u32 = 1;
pub const ARCHIVE_READDISK_HONOR_NODUMP: u32 = 2;
pub const ARCHIVE_READDISK_MAC_COPYFILE: u32 = 4;
pub const ARCHIVE_READDISK_NO_TRAVERSE_MOUNTS: u32 = 8;
pub const ARCHIVE_READDISK_NO_XATTR: u32 = 16;
pub const ARCHIVE_READDISK_NO_ACL: u32 = 32;
pub const ARCHIVE_READDISK_NO_FFLAGS: u32 = 64;
pub const ARCHIVE_READDISK_NO_SPARSE: u32 = 128;
pub const ARCHIVE_MATCH_MTIME: u32 = 256;
pub const ARCHIVE_MATCH_CTIME: u32 = 512;
pub const ARCHIVE_MATCH_NEWER: u32 = 1;
pub const ARCHIVE_MATCH_OLDER: u32 = 2;
pub const ARCHIVE_MATCH_EQUAL: u32 = 16;
pub const AE_SYMLINK_TYPE_UNDEFINED: u32 = 0;
pub const AE_SYMLINK_TYPE_FILE: u32 = 1;
pub const AE_SYMLINK_TYPE_DIRECTORY: u32 = 2;
pub const ARCHIVE_ENTRY_DIGEST_MD5: u32 = 1;
pub const ARCHIVE_ENTRY_DIGEST_RMD160: u32 = 2;
pub const ARCHIVE_ENTRY_DIGEST_SHA1: u32 = 3;
pub const ARCHIVE_ENTRY_DIGEST_SHA256: u32 = 4;
pub const ARCHIVE_ENTRY_DIGEST_SHA384: u32 = 5;
pub const ARCHIVE_ENTRY_DIGEST_SHA512: u32 = 6;
pub const ARCHIVE_ENTRY_ACL_EXECUTE: u32 = 1;
pub const ARCHIVE_ENTRY_ACL_WRITE: u32 = 2;
pub const ARCHIVE_ENTRY_ACL_READ: u32 = 4;
pub const ARCHIVE_ENTRY_ACL_READ_DATA: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_LIST_DIRECTORY: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_WRITE_DATA: u32 = 16;
pub const ARCHIVE_ENTRY_ACL_ADD_FILE: u32 = 16;
pub const ARCHIVE_ENTRY_ACL_APPEND_DATA: u32 = 32;
pub const ARCHIVE_ENTRY_ACL_ADD_SUBDIRECTORY: u32 = 32;
pub const ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS: u32 = 64;
pub const ARCHIVE_ENTRY_ACL_WRITE_NAMED_ATTRS: u32 = 128;
pub const ARCHIVE_ENTRY_ACL_DELETE_CHILD: u32 = 256;
pub const ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES: u32 = 512;
pub const ARCHIVE_ENTRY_ACL_WRITE_ATTRIBUTES: u32 = 1024;
pub const ARCHIVE_ENTRY_ACL_DELETE: u32 = 2048;
pub const ARCHIVE_ENTRY_ACL_READ_ACL: u32 = 4096;
pub const ARCHIVE_ENTRY_ACL_WRITE_ACL: u32 = 8192;
pub const ARCHIVE_ENTRY_ACL_WRITE_OWNER: u32 = 16384;
pub const ARCHIVE_ENTRY_ACL_SYNCHRONIZE: u32 = 32768;
pub const ARCHIVE_ENTRY_ACL_PERMS_POSIX1E: u32 = 7;
pub const ARCHIVE_ENTRY_ACL_PERMS_NFS4: u32 = 65529;
pub const ARCHIVE_ENTRY_ACL_ENTRY_INHERITED: u32 = 16777216;
pub const ARCHIVE_ENTRY_ACL_ENTRY_FILE_INHERIT: u32 = 33554432;
pub const ARCHIVE_ENTRY_ACL_ENTRY_DIRECTORY_INHERIT: u32 = 67108864;
pub const ARCHIVE_ENTRY_ACL_ENTRY_NO_PROPAGATE_INHERIT: u32 = 134217728;
pub const ARCHIVE_ENTRY_ACL_ENTRY_INHERIT_ONLY: u32 = 268435456;
pub const ARCHIVE_ENTRY_ACL_ENTRY_SUCCESSFUL_ACCESS: u32 = 536870912;
pub const ARCHIVE_ENTRY_ACL_ENTRY_FAILED_ACCESS: u32 = 1073741824;
pub const ARCHIVE_ENTRY_ACL_INHERITANCE_NFS4: u32 = 2130706432;
pub const ARCHIVE_ENTRY_ACL_TYPE_ACCESS: u32 = 256;
pub const ARCHIVE_ENTRY_ACL_TYPE_DEFAULT: u32 = 512;
pub const ARCHIVE_ENTRY_ACL_TYPE_ALLOW: u32 = 1024;
pub const ARCHIVE_ENTRY_ACL_TYPE_DENY: u32 = 2048;
pub const ARCHIVE_ENTRY_ACL_TYPE_AUDIT: u32 = 4096;
pub const ARCHIVE_ENTRY_ACL_TYPE_ALARM: u32 = 8192;
pub const ARCHIVE_ENTRY_ACL_TYPE_POSIX1E: u32 = 768;
pub const ARCHIVE_ENTRY_ACL_TYPE_NFS4: u32 = 15360;
pub const ARCHIVE_ENTRY_ACL_USER: u32 = 10001;
pub const ARCHIVE_ENTRY_ACL_USER_OBJ: u32 = 10002;
pub const ARCHIVE_ENTRY_ACL_GROUP: u32 = 10003;
pub const ARCHIVE_ENTRY_ACL_GROUP_OBJ: u32 = 10004;
pub const ARCHIVE_ENTRY_ACL_MASK: u32 = 10005;
pub const ARCHIVE_ENTRY_ACL_OTHER: u32 = 10006;
pub const ARCHIVE_ENTRY_ACL_EVERYONE: u32 = 10107;
pub const ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID: u32 = 1;
pub const ARCHIVE_ENTRY_ACL_STYLE_MARK_DEFAULT: u32 = 2;
pub const ARCHIVE_ENTRY_ACL_STYLE_SOLARIS: u32 = 4;
pub const ARCHIVE_ENTRY_ACL_STYLE_SEPARATOR_COMMA: u32 = 8;
pub const ARCHIVE_ENTRY_ACL_STYLE_COMPACT: u32 = 16;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_time_t = i64; // Fixed for Windows: time_t is 64-bit on both macOS and Win64 MSVC
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_uid_t = __uint32_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __darwin_time_t,
    pub tv_nsec: ::std::os::raw::c_long,
}
pub type blkcnt_t = __darwin_blkcnt_t;
pub type blksize_t = __darwin_blksize_t;
pub type dev_t = __darwin_dev_t;
pub type mode_t = __darwin_mode_t;
pub type nlink_t = __uint16_t;
pub type uid_t = __darwin_uid_t;
pub type gid_t = __darwin_gid_t;
pub type off_t = __darwin_off_t;
pub type time_t = __darwin_time_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct stat {
    pub st_dev: dev_t,
    pub st_mode: mode_t,
    pub st_nlink: nlink_t,
    pub st_ino: __darwin_ino64_t,
    pub st_uid: uid_t,
    pub st_gid: gid_t,
    pub st_rdev: dev_t,
    pub st_atimespec: timespec,
    pub st_mtimespec: timespec,
    pub st_ctimespec: timespec,
    pub st_birthtimespec: timespec,
    pub st_size: off_t,
    pub st_blocks: blkcnt_t,
    pub st_blksize: blksize_t,
    pub st_flags: __uint32_t,
    pub st_gen: __uint32_t,
    pub st_lspare: __int32_t,
    pub st_qspare: [__int64_t; 2usize],
}
pub type wchar_t = ::std::os::raw::c_int;
pub type fpos_t = __darwin_off_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sbuf {
    pub _base: *mut ::std::os::raw::c_uchar,
    pub _size: ::std::os::raw::c_int,
}
impl Default for __sbuf {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILEX {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILE {
    pub _p: *mut ::std::os::raw::c_uchar,
    pub _r: ::std::os::raw::c_int,
    pub _w: ::std::os::raw::c_int,
    pub _flags: ::std::os::raw::c_short,
    pub _file: ::std::os::raw::c_short,
    pub _bf: __sbuf,
    pub _lbfsize: ::std::os::raw::c_int,
    pub _cookie: *mut ::std::os::raw::c_void,
    pub _close: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub _read: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *mut ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _seek: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: fpos_t,
            arg3: ::std::os::raw::c_int,
        ) -> fpos_t,
    >,
    pub _write: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _ub: __sbuf,
    pub _extra: *mut __sFILEX,
    pub _ur: ::std::os::raw::c_int,
    pub _ubuf: [::std::os::raw::c_uchar; 3usize],
    pub _nbuf: [::std::os::raw::c_uchar; 1usize],
    pub _lb: __sbuf,
    pub _blksize: ::std::os::raw::c_int,
    pub _offset: fpos_t,
}
impl Default for __sFILE {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FILE = __sFILE;
pub type la_int64_t = i64;
pub type la_ssize_t = isize;
unsafe extern "C" {
    pub fn archive_version_number() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_version_string() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_version_details() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_zlib_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_liblzma_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_bzlib_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_liblz4_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libzstd_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_liblzo2_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libexpat_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libbsdxml_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libxml2_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_mbedtls_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_nettle_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_openssl_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libmd_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_commoncrypto_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_cng_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_wincrypt_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_librichacl_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libacl_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libattr_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libiconv_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libpcre_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_libpcre2_version() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_entry {
    _unused: [u8; 0],
}
pub type archive_read_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        _buffer: *mut *const ::std::os::raw::c_void,
    ) -> la_ssize_t,
>;
pub type archive_skip_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        request: la_int64_t,
    ) -> la_int64_t,
>;
pub type archive_seek_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        offset: la_int64_t,
        whence: ::std::os::raw::c_int,
    ) -> la_int64_t,
>;
pub type archive_write_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        _buffer: *const ::std::os::raw::c_void,
        _length: usize,
    ) -> la_ssize_t,
>;
pub type archive_open_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type archive_close_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type archive_free_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type archive_switch_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data1: *mut ::std::os::raw::c_void,
        _client_data2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type archive_passphrase_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char,
>;
unsafe extern "C" {
    pub fn archive_read_new() -> *mut archive;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_program(
        arg1: *mut archive,
        command: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_rpm(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_uu(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_by_code(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_grzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_lrzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_lz4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_lzop(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_program(
        arg1: *mut archive,
        command: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_rpm(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_uu(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_filter_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_7zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_all(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_ar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_by_code(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_cab(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_cpio(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_empty(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_gnutar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_iso9660(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_lha(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_mtree(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_rar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_rar5(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_raw(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_tar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_warc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_xar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_zip_streamable(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_support_format_zip_seekable(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_format(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_append_filter(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_append_filter_program(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_append_filter_program_signature(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_open_callback(
        arg1: *mut archive,
        arg2: archive_open_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_read_callback(
        arg1: *mut archive,
        arg2: archive_read_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_seek_callback(
        arg1: *mut archive,
        arg2: archive_seek_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_skip_callback(
        arg1: *mut archive,
        arg2: archive_skip_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_close_callback(
        arg1: *mut archive,
        arg2: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_switch_callback(
        arg1: *mut archive,
        arg2: archive_switch_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_callback_data2(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_add_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_append_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_prepend_callback_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open1(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        arg2: archive_open_callback,
        arg3: archive_read_callback,
        arg4: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open2(
        arg1: *mut archive,
        _client_data: *mut ::std::os::raw::c_void,
        arg2: archive_open_callback,
        arg3: archive_read_callback,
        arg4: archive_skip_callback,
        arg5: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_filename(
        arg1: *mut archive,
        _filename: *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_filenames(
        arg1: *mut archive,
        _filenames: *mut *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_filename_w(
        arg1: *mut archive,
        _filename: *const wchar_t,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_file(
        arg1: *mut archive,
        _filename: *const ::std::os::raw::c_char,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_memory(
        arg1: *mut archive,
        buff: *const ::std::os::raw::c_void,
        size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_memory2(
        a: *mut archive,
        buff: *const ::std::os::raw::c_void,
        size: usize,
        read_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_fd(
        arg1: *mut archive,
        _fd: ::std::os::raw::c_int,
        _block_size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_open_FILE(arg1: *mut archive, _file: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_next_header(
        arg1: *mut archive,
        arg2: *mut *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_next_header2(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_header_position(arg1: *mut archive) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_read_has_encrypted_entries(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_format_capabilities(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_data(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: usize,
    ) -> la_ssize_t;
}
unsafe extern "C" {
    pub fn archive_seek_data(
        arg1: *mut archive,
        arg2: la_int64_t,
        arg3: ::std::os::raw::c_int,
    ) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_read_data_block(
        a: *mut archive,
        buff: *mut *const ::std::os::raw::c_void,
        size: *mut usize,
        offset: *mut la_int64_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_data_skip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_data_into_fd(
        arg1: *mut archive,
        fd: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_format_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_filter_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_options(
        _a: *mut archive,
        opts: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_add_passphrase(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_set_passphrase_callback(
        arg1: *mut archive,
        client_data: *mut ::std::os::raw::c_void,
        arg2: archive_passphrase_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_extract(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_extract2(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        arg3: *mut archive,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_extract_set_progress_callback(
        arg1: *mut archive,
        _progress_func: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void),
        >,
        _user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn archive_read_extract_set_skip_file(
        arg1: *mut archive,
        arg2: la_int64_t,
        arg3: la_int64_t,
    );
}
unsafe extern "C" {
    pub fn archive_read_close(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_finish(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_new() -> *mut archive;
}
unsafe extern "C" {
    pub fn archive_write_set_bytes_per_block(
        arg1: *mut archive,
        bytes_per_block: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_get_bytes_per_block(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_bytes_in_last_block(
        arg1: *mut archive,
        bytes_in_last_block: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_get_bytes_in_last_block(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_skip_file(
        arg1: *mut archive,
        arg2: la_int64_t,
        arg3: la_int64_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_program(
        arg1: *mut archive,
        cmd: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter(
        arg1: *mut archive,
        filter_code: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_by_name(
        arg1: *mut archive,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_b64encode(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_compress(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_grzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_gzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_lrzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_lz4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_lzip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_lzop(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_none(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_program(
        arg1: *mut archive,
        cmd: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_uuencode(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_add_filter_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format(
        arg1: *mut archive,
        format_code: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_by_name(
        arg1: *mut archive,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_7zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_ar_bsd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_ar_svr4(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_cpio(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_cpio_bin(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_cpio_newc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_cpio_odc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_cpio_pwb(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_gnutar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_iso9660(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_mtree(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_mtree_classic(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_pax(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_pax_restricted(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_raw(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_shar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_shar_dump(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_ustar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_v7tar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_warc(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_xar(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_zip(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_filter_by_ext(
        a: *mut archive,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_filter_by_ext_def(
        a: *mut archive,
        filename: *const ::std::os::raw::c_char,
        def_ext: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_deflate(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_store(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_lzma(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_xz(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_bzip2(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_zip_set_compression_zstd(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: archive_open_callback,
        arg4: archive_write_callback,
        arg5: archive_close_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open2(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: archive_open_callback,
        arg4: archive_write_callback,
        arg5: archive_close_callback,
        arg6: archive_free_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_fd(
        arg1: *mut archive,
        _fd: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_filename(
        arg1: *mut archive,
        _file: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_filename_w(
        arg1: *mut archive,
        _file: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_file(
        arg1: *mut archive,
        _file: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_FILE(arg1: *mut archive, arg2: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_open_memory(
        arg1: *mut archive,
        _buffer: *mut ::std::os::raw::c_void,
        _buffSize: usize,
        _used: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_header(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_data(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    ) -> la_ssize_t;
}
unsafe extern "C" {
    pub fn archive_write_data_block(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
        arg4: la_int64_t,
    ) -> la_ssize_t;
}
unsafe extern "C" {
    pub fn archive_write_finish_entry(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_close(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_fail(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_finish(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_format_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_filter_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_option(
        _a: *mut archive,
        m: *const ::std::os::raw::c_char,
        o: *const ::std::os::raw::c_char,
        v: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_options(
        _a: *mut archive,
        opts: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_passphrase(
        _a: *mut archive,
        p: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_set_passphrase_callback(
        arg1: *mut archive,
        client_data: *mut ::std::os::raw::c_void,
        arg2: archive_passphrase_callback,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_new() -> *mut archive;
}
unsafe extern "C" {
    pub fn archive_write_disk_set_skip_file(
        arg1: *mut archive,
        arg2: la_int64_t,
        arg3: la_int64_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_set_options(
        arg1: *mut archive,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_set_standard_lookup(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_set_group_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_char,
                arg3: la_int64_t,
            ) -> la_int64_t,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_set_user_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_char,
                arg3: la_int64_t,
            ) -> la_int64_t,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_write_disk_gid(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: la_int64_t,
    ) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_write_disk_uid(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        arg3: la_int64_t,
    ) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_read_disk_new() -> *mut archive;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_symlink_logical(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_symlink_physical(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_symlink_hybrid(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_entry_from_file(
        arg1: *mut archive,
        arg2: *mut archive_entry,
        arg3: ::std::os::raw::c_int,
        arg4: *const stat,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_gname(
        arg1: *mut archive,
        arg2: la_int64_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_read_disk_uname(
        arg1: *mut archive,
        arg2: la_int64_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_standard_lookup(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_gname_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: la_int64_t,
            ) -> *const ::std::os::raw::c_char,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_uname_lookup(
        arg1: *mut archive,
        arg2: *mut ::std::os::raw::c_void,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: la_int64_t,
            ) -> *const ::std::os::raw::c_char,
        >,
        arg4: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_open(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_open_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_descend(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_can_descend(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_current_filesystem(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_current_filesystem_is_synthetic(
        arg1: *mut archive,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_current_filesystem_is_remote(
        arg1: *mut archive,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_atime_restored(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_behavior(
        arg1: *mut archive,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_matching(
        arg1: *mut archive,
        _matching: *mut archive,
        _excluded_func: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut archive,
                arg2: *mut ::std::os::raw::c_void,
                arg3: *mut archive_entry,
            ),
        >,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_read_disk_set_metadata_filter_callback(
        arg1: *mut archive,
        _metadata_filter_func: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut archive,
                arg2: *mut ::std::os::raw::c_void,
                arg3: *mut archive_entry,
            ) -> ::std::os::raw::c_int,
        >,
        _client_data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_filter_count(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_filter_bytes(arg1: *mut archive, arg2: ::std::os::raw::c_int) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_filter_code(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_filter_name(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_position_compressed(arg1: *mut archive) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_position_uncompressed(arg1: *mut archive) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_compression_name(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_compression(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_parse_date(now: time_t, datestr: *const ::std::os::raw::c_char) -> time_t;
}
unsafe extern "C" {
    pub fn archive_errno(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_error_string(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_format_name(arg1: *mut archive) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_format(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_clear_error(arg1: *mut archive);
}
unsafe extern "C" {
    pub fn archive_set_error(
        arg1: *mut archive,
        _err: ::std::os::raw::c_int,
        fmt: *const ::std::os::raw::c_char,
        ...
    );
}
unsafe extern "C" {
    pub fn archive_copy_error(dest: *mut archive, src: *mut archive);
}
unsafe extern "C" {
    pub fn archive_file_count(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_new() -> *mut archive;
}
unsafe extern "C" {
    pub fn archive_match_free(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_excluded(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_path_excluded(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_set_inclusion_recursion(
        arg1: *mut archive,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_exclude_pattern(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_exclude_pattern_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_exclude_pattern_from_file(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_exclude_pattern_from_file_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_pattern(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_pattern_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_pattern_from_file(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_pattern_from_file_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
        _nullSeparator: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_path_unmatched_inclusions(arg1: *mut archive) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_path_unmatched_inclusions_next(
        arg1: *mut archive,
        arg2: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_path_unmatched_inclusions_next_w(
        arg1: *mut archive,
        arg2: *mut *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_time_excluded(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_time(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _sec: time_t,
        _nsec: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_date(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _datestr: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_date_w(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _datestr: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_file_time(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _pathname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_file_time_w(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        _pathname: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_exclude_entry(
        arg1: *mut archive,
        _flag: ::std::os::raw::c_int,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_owner_excluded(
        arg1: *mut archive,
        arg2: *mut archive_entry,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_uid(arg1: *mut archive, arg2: la_int64_t)
    -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_gid(arg1: *mut archive, arg2: la_int64_t)
    -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_uname(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_uname_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_gname(
        arg1: *mut archive,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_match_include_gname_w(
        arg1: *mut archive,
        arg2: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_utility_string_sort(
        arg1: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_clear(arg1: *mut archive_entry) -> *mut archive_entry;
}
unsafe extern "C" {
    pub fn archive_entry_clone(arg1: *mut archive_entry) -> *mut archive_entry;
}
unsafe extern "C" {
    pub fn archive_entry_free(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_new() -> *mut archive_entry;
}
unsafe extern "C" {
    pub fn archive_entry_new2(arg1: *mut archive) -> *mut archive_entry;
}
unsafe extern "C" {
    pub fn archive_entry_atime(arg1: *mut archive_entry) -> time_t;
}
unsafe extern "C" {
    pub fn archive_entry_atime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn archive_entry_atime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_birthtime(arg1: *mut archive_entry) -> time_t;
}
unsafe extern "C" {
    pub fn archive_entry_birthtime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn archive_entry_birthtime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_ctime(arg1: *mut archive_entry) -> time_t;
}
unsafe extern "C" {
    pub fn archive_entry_ctime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn archive_entry_ctime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_dev(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_dev_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_devmajor(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_devminor(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_filetype(arg1: *mut archive_entry) -> mode_t;
}
unsafe extern "C" {
    pub fn archive_entry_filetype_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_fflags(
        arg1: *mut archive_entry,
        arg2: *mut ::std::os::raw::c_ulong,
        arg3: *mut ::std::os::raw::c_ulong,
    );
}
unsafe extern "C" {
    pub fn archive_entry_fflags_text(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_gid(arg1: *mut archive_entry) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_entry_gid_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_gname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_gname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_gname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_set_link_to_hardlink(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_hardlink(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_hardlink_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_hardlink_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_hardlink_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_ino(arg1: *mut archive_entry) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_entry_ino64(arg1: *mut archive_entry) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_entry_ino_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_mode(arg1: *mut archive_entry) -> mode_t;
}
unsafe extern "C" {
    pub fn archive_entry_mtime(arg1: *mut archive_entry) -> time_t;
}
unsafe extern "C" {
    pub fn archive_entry_mtime_nsec(arg1: *mut archive_entry) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn archive_entry_mtime_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_nlink(arg1: *mut archive_entry) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn archive_entry_pathname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_pathname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_pathname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_perm(arg1: *mut archive_entry) -> mode_t;
}
unsafe extern "C" {
    pub fn archive_entry_perm_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_rdev_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_rdev(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_rdevmajor(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_rdevminor(arg1: *mut archive_entry) -> dev_t;
}
unsafe extern "C" {
    pub fn archive_entry_sourcepath(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_sourcepath_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_size(arg1: *mut archive_entry) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_entry_size_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_strmode(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_set_link_to_symlink(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_symlink(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_symlink_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_symlink_type(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_symlink_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_uid(arg1: *mut archive_entry) -> la_int64_t;
}
unsafe extern "C" {
    pub fn archive_entry_uid_is_set(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_uname(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_uname_utf8(arg1: *mut archive_entry) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_uname_w(arg1: *mut archive_entry) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_is_data_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_is_metadata_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_is_encrypted(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_atime(
        arg1: *mut archive_entry,
        arg2: time_t,
        arg3: ::std::os::raw::c_long,
    );
}
unsafe extern "C" {
    pub fn archive_entry_unset_atime(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_set_birthtime(
        arg1: *mut archive_entry,
        arg2: time_t,
        arg3: ::std::os::raw::c_long,
    );
}
unsafe extern "C" {
    pub fn archive_entry_unset_birthtime(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_set_ctime(
        arg1: *mut archive_entry,
        arg2: time_t,
        arg3: ::std::os::raw::c_long,
    );
}
unsafe extern "C" {
    pub fn archive_entry_unset_ctime(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_set_dev(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_devmajor(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_devminor(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_filetype(arg1: *mut archive_entry, arg2: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn archive_entry_set_fflags(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_ulong,
        arg3: ::std::os::raw::c_ulong,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_fflags_text(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_copy_fflags_text_len(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_copy_fflags_text_w(
        arg1: *mut archive_entry,
        arg2: *const wchar_t,
    ) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_set_gid(arg1: *mut archive_entry, arg2: la_int64_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_gname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_set_gname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_gname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_copy_gname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_gname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_hardlink(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_set_hardlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_hardlink(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_hardlink_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_hardlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_ino(arg1: *mut archive_entry, arg2: la_int64_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_ino64(arg1: *mut archive_entry, arg2: la_int64_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_link(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_set_link_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_link(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_copy_link_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_link_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_mode(arg1: *mut archive_entry, arg2: mode_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_mtime(
        arg1: *mut archive_entry,
        arg2: time_t,
        arg3: ::std::os::raw::c_long,
    );
}
unsafe extern "C" {
    pub fn archive_entry_unset_mtime(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_set_nlink(arg1: *mut archive_entry, arg2: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn archive_entry_set_pathname(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_set_pathname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_pathname(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_pathname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_pathname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_perm(arg1: *mut archive_entry, arg2: mode_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_rdev(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_rdevmajor(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_rdevminor(arg1: *mut archive_entry, arg2: dev_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_size(arg1: *mut archive_entry, arg2: la_int64_t);
}
unsafe extern "C" {
    pub fn archive_entry_unset_size(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_copy_sourcepath(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_sourcepath_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_symlink(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_set_symlink_type(arg1: *mut archive_entry, arg2: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn archive_entry_set_symlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_symlink(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_symlink_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_symlink_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_uid(arg1: *mut archive_entry, arg2: la_int64_t);
}
unsafe extern "C" {
    pub fn archive_entry_set_uname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_set_uname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_copy_uname(arg1: *mut archive_entry, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn archive_entry_copy_uname_w(arg1: *mut archive_entry, arg2: *const wchar_t);
}
unsafe extern "C" {
    pub fn archive_entry_update_uname_utf8(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_set_is_data_encrypted(
        arg1: *mut archive_entry,
        is_encrypted: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_set_is_metadata_encrypted(
        arg1: *mut archive_entry,
        is_encrypted: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn archive_entry_stat(arg1: *mut archive_entry) -> *const stat;
}
unsafe extern "C" {
    pub fn archive_entry_copy_stat(arg1: *mut archive_entry, arg2: *const stat);
}
unsafe extern "C" {
    pub fn archive_entry_mac_metadata(
        arg1: *mut archive_entry,
        arg2: *mut usize,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn archive_entry_copy_mac_metadata(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    );
}
unsafe extern "C" {
    pub fn archive_entry_digest(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_uchar;
}
unsafe extern "C" {
    pub fn archive_entry_set_digest(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_clear(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_acl_add_entry(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_add_entry_w(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: *const wchar_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_reset(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_next(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_to_text_w(
        arg1: *mut archive_entry,
        arg2: *mut la_ssize_t,
        arg3: ::std::os::raw::c_int,
    ) -> *mut wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_acl_to_text(
        arg1: *mut archive_entry,
        arg2: *mut la_ssize_t,
        arg3: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_acl_from_text_w(
        arg1: *mut archive_entry,
        arg2: *const wchar_t,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_from_text(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_text_w(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn archive_entry_acl_text(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn archive_entry_acl_types(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_acl_count(
        arg1: *mut archive_entry,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_acl {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn archive_entry_acl(arg1: *mut archive_entry) -> *mut archive_acl;
}
unsafe extern "C" {
    pub fn archive_entry_xattr_clear(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_xattr_add_entry(
        arg1: *mut archive_entry,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_void,
        arg4: usize,
    );
}
unsafe extern "C" {
    pub fn archive_entry_xattr_count(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_xattr_reset(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_xattr_next(
        arg1: *mut archive_entry,
        arg2: *mut *const ::std::os::raw::c_char,
        arg3: *mut *const ::std::os::raw::c_void,
        arg4: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_sparse_clear(arg1: *mut archive_entry);
}
unsafe extern "C" {
    pub fn archive_entry_sparse_add_entry(
        arg1: *mut archive_entry,
        arg2: la_int64_t,
        arg3: la_int64_t,
    );
}
unsafe extern "C" {
    pub fn archive_entry_sparse_count(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_sparse_reset(arg1: *mut archive_entry) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn archive_entry_sparse_next(
        arg1: *mut archive_entry,
        arg2: *mut la_int64_t,
        arg3: *mut la_int64_t,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct archive_entry_linkresolver {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn archive_entry_linkresolver_new() -> *mut archive_entry_linkresolver;
}
unsafe extern "C" {
    pub fn archive_entry_linkresolver_set_strategy(
        arg1: *mut archive_entry_linkresolver,
        arg2: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn archive_entry_linkresolver_free(arg1: *mut archive_entry_linkresolver);
}
unsafe extern "C" {
    pub fn archive_entry_linkify(
        arg1: *mut archive_entry_linkresolver,
        arg2: *mut *mut archive_entry,
        arg3: *mut *mut archive_entry,
    );
}
unsafe extern "C" {
    pub fn archive_entry_partial_links(
        res: *mut archive_entry_linkresolver,
        links: *mut ::std::os::raw::c_uint,
    ) -> *mut archive_entry;
}
